import { Doctor, Patient, Appointment, Specialty, Notification, Review, Transaction, TimeSlot, DayAvailability, VerificationDocument } from '@/types';

export const specialties: Specialty[] = [
  { id: '1', name: 'General Physician', icon: '🩺', description: 'Primary care and general health consultations', doctorCount: 45 },
  { id: '2', name: 'Cardiologist', icon: '❤️', description: 'Heart and cardiovascular system specialists', doctorCount: 23 },
  { id: '3', name: 'Dermatologist', icon: '🧴', description: 'Skin, hair, and nail conditions', doctorCount: 31 },
  { id: '4', name: 'Gynecologist', icon: '婦', description: 'Women\'s reproductive health', doctorCount: 28 },
  { id: '5', name: 'Pediatrician', icon: '👶', description: 'Children\'s health and development', doctorCount: 19 },
  { id: '6', name: 'Neurologist', icon: '🧠', description: 'Brain and nervous system disorders', doctorCount: 15 },
  { id: '7', name: 'Orthopedic', icon: '🦴', description: 'Bones, joints, and musculoskeletal system', doctorCount: 22 },
  { id: '8', name: 'Dentist', icon: '🦷', description: 'Dental and oral health care', doctorCount: 34 },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@telemed.com',
    phone: '+1 (555) 123-4567',
    role: 'doctor',
    avatar: '/avatars/doctor-1.jpg',
    specialty: 'Cardiologist',
    qualification: 'MD, FACC',
    degree: 'Harvard Medical School',
    experience: 15,
    consultationFee: 150,
    languages: ['English', 'Spanish'],
    bio: 'Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience in diagnosing and treating cardiovascular diseases. She specializes in preventive cardiology, heart failure management, and cardiac imaging. Dr. Johnson is committed to providing patient-centered care and has published numerous research papers in leading medical journals.',
    rating: 4.9,
    reviewCount: 287,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['Board Certified Cardiologist', 'Advanced Cardiac Life Support', 'Echocardiography Certified'],
    hospitalAffiliations: ['Mount Sinai Hospital', 'New York Presbyterian'],
    createdAt: '2023-01-15',
    googleCalendarConnected: true,
    availableSlots: [
      { id: 's1', date: '2026-09-01', time: '10:00 AM', available: true },
      { id: 's2', date: '2026-09-01', time: '10:30 AM', available: false, bookedBy: 'patient-1' },
      { id: 's3', date: '2026-09-01', time: '11:00 AM', available: true },
      { id: 's4', date: '2026-09-01', time: '11:30 AM', available: true },
      { id: 's5', date: '2026-09-02', time: '09:00 AM', available: true },
      { id: 's6', date: '2026-09-02', time: '09:30 AM', available: true },
      { id: 's7', date: '2026-09-02', time: '10:00 AM', available: true },
      { id: 's8', date: '2026-09-02', time: '10:30 AM', available: false, bookedBy: 'patient-2' },
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@telemed.com',
    phone: '+1 (555) 234-5678',
    role: 'doctor',
    avatar: '/avatars/doctor-2.jpg',
    specialty: 'Dermatologist',
    qualification: 'MD, FAAD',
    degree: 'Stanford University School of Medicine',
    experience: 12,
    consultationFee: 120,
    languages: ['English', 'Mandarin'],
    bio: 'Dr. Michael Chen is a fellowship-trained dermatologist specializing in medical, cosmetic, and surgical dermatology. With 12 years of clinical experience, he provides comprehensive care for conditions ranging from acne and eczema to skin cancer screening.',
    rating: 4.8,
    reviewCount: 203,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['Board Certified Dermatologist', 'Mohs Surgery Certified'],
    hospitalAffiliations: ['UCSF Medical Center'],
    createdAt: '2023-03-20',
    availableSlots: [
      { id: 's9', date: '2026-09-01', time: '02:00 PM', available: true },
      { id: 's10', date: '2026-09-01', time: '02:30 PM', available: true },
      { id: 's11', date: '2026-09-01', time: '03:00 PM', available: true },
      { id: 's12', date: '2026-09-02', time: '09:00 AM', available: true },
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@telemed.com',
    phone: '+1 (555) 345-6789',
    role: 'doctor',
    avatar: '/avatars/doctor-3.jpg',
    specialty: 'Pediatrician',
    qualification: 'MD, FAAP',
    degree: 'Johns Hopkins School of Medicine',
    experience: 10,
    consultationFee: 100,
    languages: ['English', 'Spanish', 'Portuguese'],
    bio: 'Dr. Emily Rodriguez is a compassionate pediatrician dedicated to the health and well-being of children from birth through adolescence. She has special interests in childhood developmental disorders, nutrition, and preventive care.',
    rating: 4.9,
    reviewCount: 342,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['Board Certified Pediatrician', 'Pediatric Advanced Life Support'],
    hospitalAffiliations: ['Children\'s National Medical Center'],
    createdAt: '2023-02-10',
    availableSlots: [
      { id: 's13', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's14', date: '2026-09-01', time: '09:30 AM', available: true },
      { id: 's15', date: '2026-09-01', time: '10:00 AM', available: false },
      { id: 's16', date: '2026-09-01', time: '10:30 AM', available: true },
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. James Wilson',
    email: 'james.wilson@telemed.com',
    phone: '+1 (555) 456-7890',
    role: 'doctor',
    avatar: '/avatars/doctor-4.jpg',
    specialty: 'General Physician',
    qualification: 'MD',
    degree: 'Yale School of Medicine',
    experience: 20,
    consultationFee: 80,
    languages: ['English'],
    bio: 'Dr. James Wilson is a highly experienced general physician with two decades of practice. He provides comprehensive primary care services, preventive health assessments, and chronic disease management.',
    rating: 4.7,
    reviewCount: 456,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 20,
    certifications: ['Board Certified Internal Medicine', 'Advanced Cardiac Life Support'],
    hospitalAffiliations: ['Mayo Clinic'],
    createdAt: '2022-11-05',
    availableSlots: [
      { id: 's17', date: '2026-09-01', time: '08:00 AM', available: true },
      { id: 's18', date: '2026-09-01', time: '08:30 AM', available: true },
      { id: 's19', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's20', date: '2026-09-02', time: '08:00 AM', available: true },
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Priya Patel',
    email: 'priya.patel@telemed.com',
    phone: '+1 (555) 567-8901',
    role: 'doctor',
    avatar: '/avatars/doctor-5.jpg',
    specialty: 'Gynecologist',
    qualification: 'MD, FACOG',
    degree: 'Columbia University College of Physicians and Surgeons',
    experience: 14,
    consultationFee: 130,
    languages: ['English', 'Hindi', 'Gujarati'],
    bio: 'Dr. Priya Patel is a board-certified obstetrician-gynecologist with expertise in minimally invasive surgery, reproductive endocrinology, and prenatal care. She is passionate about women\'s health across all stages of life.',
    rating: 4.8,
    reviewCount: 198,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['Board Certified OB-GYN', 'Minimally Invasive Gynecologic Surgery'],
    hospitalAffiliations: ['NYU Langone Medical Center'],
    createdAt: '2023-04-12',
    availableSlots: [
      { id: 's21', date: '2026-09-01', time: '11:00 AM', available: true },
      { id: 's22', date: '2026-09-01', time: '11:30 AM', available: true },
      { id: 's23', date: '2026-09-02', time: '10:00 AM', available: true },
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Robert Kim',
    email: 'robert.kim@telemed.com',
    phone: '+1 (555) 678-9012',
    role: 'doctor',
    avatar: '/avatars/doctor-6.jpg',
    specialty: 'Neurologist',
    qualification: 'MD, PhD',
    degree: 'MIT/Harvard Joint Program',
    experience: 18,
    consultationFee: 175,
    languages: ['English', 'Korean'],
    bio: 'Dr. Robert Kim is a dual MD-PhD neurologist specializing in neurodegenerative diseases, epilepsy, and headache medicine. He combines cutting-edge research with clinical practice to provide the best neurological care.',
    rating: 4.9,
    reviewCount: 156,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 45,
    certifications: ['Board Certified Neurologist', 'Epilepsy Special Competency'],
    hospitalAffiliations: ['Massachusetts General Hospital'],
    createdAt: '2023-01-20',
    availableSlots: [
      { id: 's24', date: '2026-09-02', time: '02:00 PM', available: true },
      { id: 's25', date: '2026-09-02', time: '03:00 PM', available: true },
    ],
  },
  {
    id: 'doc-7',
    name: 'Dr. Anna Martinez',
    email: 'anna.martinez@telemed.com',
    phone: '+1 (555) 789-0123',
    role: 'doctor',
    avatar: '/avatars/doctor-7.jpg',
    specialty: 'Orthopedic',
    qualification: 'MD, FAAOS',
    degree: 'University of Pennsylvania School of Medicine',
    experience: 16,
    consultationFee: 140,
    languages: ['English', 'Spanish'],
    bio: 'Dr. Anna Martinez is an orthopedic surgeon with extensive experience in sports medicine, joint replacement, and trauma surgery. She utilizes the latest minimally invasive techniques for optimal patient outcomes.',
    rating: 4.7,
    reviewCount: 178,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['Board Certified Orthopedic Surgery', 'Sports Medicine Fellowship'],
    hospitalAffiliations: ['Hospital for Special Surgery'],
    createdAt: '2023-05-01',
    availableSlots: [
      { id: 's26', date: '2026-09-01', time: '03:00 PM', available: true },
      { id: 's27', date: '2026-09-02', time: '11:00 AM', available: true },
    ],
  },
  {
    id: 'doc-8',
    name: 'Dr. David Thompson',
    email: 'david.thompson@telemed.com',
    phone: '+1 (555) 890-1234',
    role: 'doctor',
    avatar: '/avatars/doctor-8.jpg',
    specialty: 'Dentist',
    qualification: 'DDS, MAGD',
    degree: 'University of Michigan School of Dentistry',
    experience: 13,
    consultationFee: 90,
    languages: ['English'],
    bio: 'Dr. David Thompson is a general dentist with advanced training in restorative dentistry, dental implants, and cosmetic procedures. He is committed to providing gentle, patient-focused dental care.',
    rating: 4.6,
    reviewCount: 234,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['General Dentistry License', 'Advanced Implant Training'],
    hospitalAffiliations: [],
    createdAt: '2023-06-15',
    availableSlots: [
      { id: 's28', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's29', date: '2026-09-01', time: '09:30 AM', available: true },
      { id: 's30', date: '2026-09-01', time: '10:00 AM', available: true },
    ],
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1 (555) 111-2222',
    role: 'patient',
    avatar: '/avatars/patient-1.jpg',
    dateOfBirth: '1985-06-15',
    gender: 'Male',
    address: '123 Main St, New York, NY 10001',
    emergencyContact: 'Jane Smith',
    emergencyPhone: '+1 (555) 111-3333',
    createdAt: '2024-01-10',
  },
  {
    id: 'pat-2',
    name: 'Maria Garcia',
    email: 'maria.garcia@email.com',
    phone: '+1 (555) 222-3333',
    role: 'patient',
    avatar: '/avatars/patient-2.jpg',
    dateOfBirth: '1990-03-22',
    gender: 'Female',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    emergencyContact: 'Carlos Garcia',
    emergencyPhone: '+1 (555) 222-4444',
    createdAt: '2024-02-15',
  },
  {
    id: 'pat-3',
    name: 'David Lee',
    email: 'david.lee@email.com',
    phone: '+1 (555) 333-4444',
    role: 'patient',
    avatar: '/avatars/patient-3.jpg',
    dateOfBirth: '1978-11-08',
    gender: 'Male',
    address: '789 Pine Rd, Chicago, IL 60601',
    emergencyContact: 'Sarah Lee',
    emergencyPhone: '+1 (555) 333-5555',
    createdAt: '2024-03-01',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    doctorId: 'doc-1',
    doctor: mockDoctors[0],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-09-05',
    time: '10:00 AM',
    duration: 30,
    status: 'confirmed',
    paymentStatus: 'paid',
    consultationFee: 150,
    meetLink: 'https://meet.google.com/abc-defg-hij',
    medicalReports: [
      { id: 'mr-1', name: 'Blood Test Results', fileName: 'blood_test.pdf', fileSize: 245000, fileType: 'application/pdf', uploadedAt: '2026-09-01', url: '#' },
      { id: 'mr-2', name: 'ECG Report', fileName: 'ecg_report.pdf', fileSize: 520000, fileType: 'application/pdf', uploadedAt: '2026-09-01', url: '#' },
    ],
    createdAt: '2026-09-01',
    timeline: [
      { status: 'Booked', timestamp: '2026-09-01T10:00:00', description: 'Appointment booked successfully' },
      { status: 'Confirmed', timestamp: '2026-09-01T10:05:00', description: 'Appointment confirmed by doctor' },
    ],
  },
  {
    id: 'apt-2',
    doctorId: 'doc-3',
    doctor: mockDoctors[2],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-09-10',
    time: '09:30 AM',
    duration: 30,
    status: 'pending',
    paymentStatus: 'pending',
    consultationFee: 100,
    createdAt: '2026-09-01',
    timeline: [
      { status: 'Booked', timestamp: '2026-09-01T14:00:00', description: 'Appointment booked successfully' },
    ],
  },
  {
    id: 'apt-3',
    doctorId: 'doc-2',
    doctor: mockDoctors[1],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-08-28',
    time: '02:00 PM',
    duration: 30,
    status: 'completed',
    paymentStatus: 'paid',
    consultationFee: 120,
    meetLink: 'https://meet.google.com/xyz-uvwx-stu',
    createdAt: '2026-08-25',
    timeline: [
      { status: 'Booked', timestamp: '2026-08-25T09:00:00', description: 'Appointment booked successfully' },
      { status: 'Confirmed', timestamp: '2026-08-25T09:10:00', description: 'Appointment confirmed by doctor' },
      { status: 'Completed', timestamp: '2026-08-28T14:30:00', description: 'Consultation completed' },
    ],
  },
  {
    id: 'apt-4',
    doctorId: 'doc-4',
    doctor: mockDoctors[3],
    patientId: 'pat-2',
    patient: mockPatients[1],
    date: '2026-08-20',
    time: '11:00 AM',
    duration: 20,
    status: 'cancelled',
    paymentStatus: 'refunded',
    consultationFee: 80,
    createdAt: '2026-08-18',
    timeline: [
      { status: 'Booked', timestamp: '2026-08-18T15:00:00', description: 'Appointment booked successfully' },
      { status: 'Cancelled', timestamp: '2026-08-19T10:00:00', description: 'Appointment cancelled by patient' },
    ],
  },
];

export const mockReviews: Review[] = [
  { id: 'rev-1', patientId: 'pat-1', patientName: 'John Smith', doctorId: 'doc-1', rating: 5, comment: 'Dr. Johnson is incredibly knowledgeable and caring. She took the time to explain my condition thoroughly and provided a comprehensive treatment plan. The online consultation was seamless.', createdAt: '2026-08-20' },
  { id: 'rev-2', patientId: 'pat-2', patientName: 'Maria Garcia', doctorId: 'doc-1', rating: 5, comment: 'Excellent experience! Dr. Johnson was professional, attentive, and made me feel very comfortable. Highly recommended for cardiology consultations.', createdAt: '2026-08-15' },
  { id: 'rev-3', patientId: 'pat-3', patientName: 'David Lee', doctorId: 'doc-1', rating: 4, comment: 'Very thorough consultation. Dr. Johnson reviewed my reports carefully and provided clear guidance. The video quality was excellent.', createdAt: '2026-08-10' },
  { id: 'rev-4', patientId: 'pat-1', patientName: 'John Smith', doctorId: 'doc-2', rating: 5, comment: 'Dr. Chen resolved my skin concerns efficiently. Great bedside manner and very professional.', createdAt: '2026-08-28' },
  { id: 'rev-5', patientId: 'pat-2', patientName: 'Maria Garcia', doctorId: 'doc-3', rating: 5, comment: 'Dr. Rodriguez is amazing with kids! My daughter felt at ease during the entire consultation. A wonderful pediatrician.', createdAt: '2026-08-22' },
];

export const mockNotifications: Notification[] = [
  { id: 'n1', userId: 'pat-1', title: 'Appointment Confirmed', message: 'Your appointment with Dr. Sarah Johnson on Sep 5 has been confirmed.', type: 'success', read: false, createdAt: '2026-09-01T10:05:00', link: '/patient/appointments/apt-1' },
  { id: 'n2', userId: 'pat-1', title: 'Appointment Reminder', message: 'Your consultation with Dr. Michael Chen starts in 15 minutes.', type: 'info', read: false, createdAt: '2026-08-28T13:45:00', link: '/patient/appointments/apt-3' },
  { id: 'n3', userId: 'pat-1', title: 'Payment Received', message: 'Payment of $150 for appointment with Dr. Sarah Johnson has been processed.', type: 'success', read: true, createdAt: '2026-09-01T10:06:00' },
  { id: 'n4', userId: 'doc-1', title: 'New Booking', message: 'John Smith has booked an appointment for Sep 5 at 10:00 AM.', type: 'info', read: false, createdAt: '2026-09-01T10:00:00', link: '/doctor/appointments' },
  { id: 'n5', userId: 'admin', title: 'Verification Request', message: 'Dr. Lisa Wang has submitted a new verification request.', type: 'warning', read: false, createdAt: '2026-09-01T08:00:00', link: '/admin/doctor-verification' },
  { id: 'n6', userId: 'admin', title: 'New Registration', message: 'A new patient account has been registered.', type: 'info', read: true, createdAt: '2026-09-01T07:30:00' },
];

export const mockTransactions: Transaction[] = [
  { id: 'txn-1', appointmentId: 'apt-1', doctorId: 'doc-1', doctorName: 'Dr. Sarah Johnson', patientId: 'pat-1', patientName: 'John Smith', amount: 150, status: 'paid', date: '2026-09-01' },
  { id: 'txn-2', appointmentId: 'apt-3', doctorId: 'doc-2', doctorName: 'Dr. Michael Chen', patientId: 'pat-1', patientName: 'John Smith', amount: 120, status: 'paid', date: '2026-08-28' },
  { id: 'txn-3', appointmentId: 'apt-4', doctorId: 'doc-4', doctorName: 'Dr. James Wilson', patientId: 'pat-2', patientName: 'Maria Garcia', amount: 80, status: 'refunded', date: '2026-08-20' },
];

export const pendingVerificationDoctors: Doctor[] = [
  {
    id: 'doc-9',
    name: 'Dr. Lisa Wang',
    email: 'lisa.wang@email.com',
    phone: '+1 (555) 999-0001',
    role: 'doctor',
    specialty: 'Cardiologist',
    qualification: 'MD',
    degree: 'Duke University School of Medicine',
    experience: 8,
    consultationFee: 130,
    languages: ['English', 'Mandarin'],
    bio: 'Cardiologist with 8 years of experience.',
    rating: 0,
    reviewCount: 0,
    verificationStatus: 'pending',
    verified: false,
    consultationDuration: 30,
    availableSlots: [],
    createdAt: '2026-08-30',
    documents: [
      { id: 'd1', type: 'Medical License', name: 'Medical License', fileName: 'medical_license.pdf', fileSize: 340000, uploadedAt: '2026-08-30', url: '#' },
      { id: 'd2', type: 'Medical Degree', name: 'MD Certificate', fileName: 'md_certificate.pdf', fileSize: 520000, uploadedAt: '2026-08-30', url: '#' },
      { id: 'd3', type: 'National ID', name: 'Passport', fileName: 'passport.pdf', fileSize: 280000, uploadedAt: '2026-08-30', url: '#' },
    ],
  },
  {
    id: 'doc-10',
    name: 'Dr. Ahmed Hassan',
    email: 'ahmed.hassan@email.com',
    phone: '+1 (555) 999-0002',
    role: 'doctor',
    specialty: 'Dermatologist',
    qualification: 'MD, FAAD',
    degree: 'University of Michigan',
    experience: 6,
    consultationFee: 110,
    languages: ['English', 'Arabic'],
    bio: 'Dermatologist specializing in cosmetic and medical dermatology.',
    rating: 0,
    reviewCount: 0,
    verificationStatus: 'pending',
    verified: false,
    consultationDuration: 30,
    availableSlots: [],
    createdAt: '2026-08-29',
    documents: [
      { id: 'd4', type: 'Medical License', name: 'Medical License', fileName: 'license.pdf', fileSize: 310000, uploadedAt: '2026-08-29', url: '#' },
      { id: 'd5', type: 'Medical Degree', name: 'MD Certificate', fileName: 'degree.pdf', fileSize: 490000, uploadedAt: '2026-08-29', url: '#' },
    ],
  },
];

export const defaultAvailability: DayAvailability[] = [
  { day: 'sunday', available: false, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'monday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'tuesday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'wednesday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'thursday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'friday', available: true, startTime: '09:00', endTime: '15:00', slotDuration: 30 },
  { day: 'saturday', available: false, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
];

export const monthlyRevenueData = [
  { month: 'Apr', revenue: 8500 },
  { month: 'May', revenue: 12300 },
  { month: 'Jun', revenue: 15600 },
  { month: 'Jul', revenue: 18200 },
  { month: 'Aug', revenue: 21400 },
  { month: 'Sep', revenue: 19800 },
];

export const appointmentStatsData = [
  { month: 'Apr', appointments: 45 },
  { month: 'May', appointments: 62 },
  { month: 'Jun', appointments: 78 },
  { month: 'Jul', appointments: 95 },
  { month: 'Aug', appointments: 112 },
  { month: 'Sep', appointments: 98 },
];

export const doctorGrowthData = [
  { month: 'Apr', doctors: 12 },
  { month: 'May', doctors: 18 },
  { month: 'Jun', doctors: 24 },
  { month: 'Jul', doctors: 32 },
  { month: 'Aug', doctors: 38 },
  { month: 'Sep', doctors: 42 },
];

export const patientGrowthData = [
  { month: 'Apr', patients: 85 },
  { month: 'May', patients: 124 },
  { month: 'Jun', patients: 186 },
  { month: 'Jul', patients: 245 },
  { month: 'Aug', patients: 312 },
  { month: 'Sep', patients: 389 },
];
