import { Doctor, Patient, Appointment, Specialty, Notification, Review, Transaction, TimeSlot, DayAvailability, VerificationDocument } from '@/types';

export const specialties: Specialty[] = [
  { id: '1', name: 'General Physician', icon: '🩺', description: 'Primary care and general health consultations', doctorCount: 45 },
  { id: '2', name: 'Medicine Specialist', icon: '💊', description: 'Internal medicine and chronic disease management', doctorCount: 38 },
  { id: '3', name: 'Cardiologist', icon: '❤️', description: 'Heart and cardiovascular system specialists', doctorCount: 23 },
  { id: '4', name: 'Dermatologist', icon: '🧴', description: 'Skin, hair, and nail conditions', doctorCount: 31 },
  { id: '5', name: 'Gynecologist', icon: '婦', description: 'Women\'s reproductive health', doctorCount: 28 },
  { id: '6', name: 'Pediatrician', icon: '👶', description: 'Children\'s health and development', doctorCount: 19 },
  { id: '7', name: 'Neurologist', icon: '🧠', description: 'Brain and nervous system disorders', doctorCount: 15 },
  { id: '8', name: 'Orthopedic', icon: '🦴', description: 'Bones, joints, and musculoskeletal system', doctorCount: 22 },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Rafiq Ahmed',
    email: 'rafiq.ahmed@mediconnect.com',
    phone: '+880 1712-345678',
    role: 'doctor',
    avatar: '/avatars/doctor-1.jpg',
    specialty: 'Cardiologist',
    qualification: 'MBBS, FCPS (Cardiology)',
    degree: 'Dhaka Medical College',
    experience: 15,
    consultationFee: 1500,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Rafiq Ahmed is a senior cardiologist with over 15 years of experience in diagnosing and treating heart diseases. He is a Fellow of the College of Physicians and Surgeons (FCPS) and specializes in interventional cardiology and heart failure management.',
    rating: 4.9,
    reviewCount: 287,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['FCPS Cardiology', 'DM Cardiology', 'BSCPR Certified'],
    hospitalAffiliations: ['Square Hospital, Dhaka', 'National Heart Foundation'],
    createdAt: '2023-01-15',
    googleCalendarConnected: true,
    availableSlots: [
      { id: 's1', date: '2026-09-01', time: '10:00 AM', available: true },
      { id: 's2', date: '2026-09-01', time: '10:30 AM', available: false, bookedBy: 'patient-1' },
      { id: 's3', date: '2026-09-01', time: '11:00 AM', available: true },
      { id: 's4', date: '2026-09-01', time: '11:30 AM', available: true },
      { id: 's5', date: '2026-09-02', time: '09:00 AM', available: true },
      { id: 's6', date: '2026-09-02', time: '09:30 AM', available: true },
      { id: 's7', date: '2026-09-02', time: '10:00 AM', available: true },
      { id: 's8', date: '2026-09-02', time: '10:30 AM', available: false, bookedBy: 'patient-2' },
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Nusrat Jahan',
    email: 'nusrat.jahan@mediconnect.com',
    phone: '+880 1812-345678',
    role: 'doctor',
    avatar: '/avatars/doctor-2.jpg',
    specialty: 'Dermatologist',
    qualification: 'MBBS, DD (Dermatology)',
    degree: 'Bangabandhu Sheikh Mujib Medical University',
    experience: 12,
    consultationFee: 1200,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Nusrat Jahan is a experienced dermatologist specializing in medical and cosmetic dermatology. With 12 years of clinical experience, she provides comprehensive care for skin conditions, acne treatment, and skin allergy management.',
    rating: 4.8,
    reviewCount: 203,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['DD Dermatology', 'FCPS (Dermatology)'],
    hospitalAffiliations: ['Apollo Hospital, Dhaka'],
    createdAt: '2023-03-20',
    availableSlots: [
      { id: 's9', date: '2026-09-01', time: '02:00 PM', available: true },
      { id: 's10', date: '2026-09-01', time: '02:30 PM', available: true },
      { id: 's11', date: '2026-09-01', time: '03:00 PM', available: true },
      { id: 's12', date: '2026-09-02', time: '09:00 AM', available: true },
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Fatema Begum',
    email: 'fatema.begum@mediconnect.com',
    phone: '+880 1912-345678',
    role: 'doctor',
    avatar: '/avatars/doctor-3.jpg',
    specialty: 'Pediatrician',
    qualification: 'MBBS, DCH, FCPS (Pediatrics)',
    degree: 'Chittagong Medical College',
    experience: 10,
    consultationFee: 1000,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Fatema Begum is a compassionate pediatrician dedicated to the health and well-being of children from birth through adolescence. She has special interests in childhood developmental disorders, nutrition, and preventive care.',
    rating: 4.9,
    reviewCount: 342,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['FCPS Pediatrics', 'DCH', 'PALS Certified'],
    hospitalAffiliations: ['Children\'s Hospital, Dhaka', 'Square Hospital'],
    createdAt: '2023-02-10',
    availableSlots: [
      { id: 's13', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's14', date: '2026-09-01', time: '09:30 AM', available: true },
      { id: 's15', date: '2026-09-01', time: '10:00 AM', available: false },
      { id: 's16', date: '2026-09-01', time: '10:30 AM', available: true },
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. Kamal Hossain',
    email: 'kamal.hossain@mediconnect.com',
    phone: '+880 1612-345678',
    role: 'doctor',
    avatar: '/avatars/doctor-4.jpg',
    specialty: 'General Physician',
    qualification: 'MBBS, BCS (Health)',
    degree: 'Sir Salimullah Medical College',
    experience: 20,
    consultationFee: 800,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Kamal Hossain is a highly experienced general physician with two decades of practice. He provides comprehensive primary care services, preventive health assessments, and chronic disease management.',
    rating: 4.7,
    reviewCount: 456,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 20,
    certifications: ['BCS Health', 'MBBS'],
    hospitalAffiliations: ['Dhaka Medical College Hospital'],
    createdAt: '2022-11-05',
    availableSlots: [
      { id: 's17', date: '2026-09-01', time: '08:00 AM', available: true },
      { id: 's18', date: '2026-09-01', time: '08:30 AM', available: true },
      { id: 's19', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's20', date: '2026-09-02', time: '08:00 AM', available: true },
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Nasrin Akter',
    email: 'nasrin.akter@mediconnect.com',
    phone: '+880 1712-987654',
    role: 'doctor',
    avatar: '/avatars/doctor-5.jpg',
    specialty: 'Gynecologist',
    qualification: 'MBBS, FCPS (OB-GYN)',
    degree: 'Dhaka Medical College',
    experience: 14,
    consultationFee: 1300,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Nasrin Akter is a board-certified gynecologist with expertise in minimally invasive surgery, reproductive health, and prenatal care. She is passionate about women\'s health across all stages of life.',
    rating: 4.8,
    reviewCount: 198,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['FCPS OB-GYN', 'MCPS'],
    hospitalAffiliations: ['United Hospital, Dhaka'],
    createdAt: '2023-04-12',
    availableSlots: [
      { id: 's21', date: '2026-09-01', time: '11:00 AM', available: true },
      { id: 's22', date: '2026-09-01', time: '11:30 AM', available: true },
      { id: 's23', date: '2026-09-02', time: '10:00 AM', available: true },
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Tanvir Rahman',
    email: 'tanvir.rahman@mediconnect.com',
    phone: '+880 1812-987654',
    role: 'doctor',
    avatar: '/avatars/doctor-6.jpg',
    specialty: 'Neurologist',
    qualification: 'MBBS, FCPS (Neurology), MD',
    degree: 'BSMMU',
    experience: 18,
    consultationFee: 1800,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Tanvir Rahman is an experienced neurologist specializing in stroke management, epilepsy, and headache disorders. He combines clinical expertise with the latest neurological research.',
    rating: 4.9,
    reviewCount: 156,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 45,
    certifications: ['FCPS Neurology', 'MD Neurology'],
    hospitalAffiliations: ['National Institute of Neurosciences & Hospital'],
    createdAt: '2023-01-20',
    availableSlots: [
      { id: 's24', date: '2026-09-02', time: '02:00 PM', available: true },
      { id: 's25', date: '2026-09-02', time: '03:00 PM', available: true },
    ],
  },
  {
    id: 'doc-7',
    name: 'Dr. Anisur Rahman',
    email: 'anisur.rahman@mediconnect.com',
    phone: '+880 1912-987654',
    role: 'doctor',
    avatar: '/avatars/doctor-7.jpg',
    specialty: 'Orthopedic',
    qualification: 'MBBS, MS (Orthopedics)',
    degree: 'Bangabandhu Sheikh Mujib Medical University',
    experience: 16,
    consultationFee: 1400,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Anisur Rahman is an orthopedic surgeon with extensive experience in joint replacement, sports medicine, and trauma surgery. He utilizes the latest minimally invasive techniques.',
    rating: 4.7,
    reviewCount: 178,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 30,
    certifications: ['MS Orthopedics', 'Fellowship in Joint Replacement'],
    hospitalAffiliations: ['Bangabandhu Sheikh Mujib Medical University Hospital'],
    createdAt: '2023-05-01',
    availableSlots: [
      { id: 's26', date: '2026-09-01', time: '03:00 PM', available: true },
      { id: 's27', date: '2026-09-02', time: '11:00 AM', available: true },
    ],
  },
  {
    id: 'doc-8',
    name: 'Dr. Sabrina Islam',
    email: 'sabrina.islam@mediconnect.com',
    phone: '+880 1612-987654',
    role: 'doctor',
    avatar: '/avatars/doctor-8.jpg',
    specialty: 'General Physician',
    qualification: 'MBBS, CCD',
    degree: 'Dhaka Medical College',
    experience: 8,
    consultationFee: 700,
    languages: ['Bengali', 'English'],
    bio: 'Dr. Sabrina Islam is a general physician with experience in primary care, diabetes management, and preventive medicine. She is committed to providing accessible healthcare.',
    rating: 4.6,
    reviewCount: 234,
    verificationStatus: 'approved',
    verified: true,
    consultationDuration: 20,
    certifications: ['MBBS', 'CCD'],
    hospitalAffiliations: ['Labaid Hospital, Dhaka'],
    createdAt: '2023-06-15',
    availableSlots: [
      { id: 's28', date: '2026-09-01', time: '09:00 AM', available: true },
      { id: 's29', date: '2026-09-01', time: '09:30 AM', available: true },
      { id: 's30', date: '2026-09-01', time: '10:00 AM', available: true },
    ],
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    name: 'Tanvir Hasan',
    email: 'tanvir.hasan@email.com',
    phone: '+880 1712-111222',
    role: 'patient',
    avatar: '/avatars/patient-1.jpg',
    dateOfBirth: '1985-06-15',
    gender: 'Male',
    address: '12/A, Dhanmondi, Dhaka 1205',
    emergencyContact: 'Sumaiya Hasan',
    emergencyPhone: '+880 1712-111333',
    createdAt: '2024-01-10',
  },
  {
    id: 'pat-2',
    name: 'Sabahat Karim',
    email: 'sabahat.karim@email.com',
    phone: '+880 1812-222333',
    role: 'patient',
    avatar: '/avatars/patient-2.jpg',
    dateOfBirth: '1990-03-22',
    gender: 'Female',
    address: '45, Banani, Dhaka 1213',
    emergencyContact: 'Rafiq Karim',
    emergencyPhone: '+880 1812-222444',
    createdAt: '2024-02-15',
  },
  {
    id: 'pat-3',
    name: 'Ariful Islam',
    email: 'ariful.islam@email.com',
    phone: '+880 1912-333444',
    role: 'patient',
    avatar: '/avatars/patient-3.jpg',
    dateOfBirth: '1978-11-08',
    gender: 'Male',
    address: '78, Uttara, Dhaka 1230',
    emergencyContact: 'Nazma Islam',
    emergencyPhone: '+880 1912-333555',
    createdAt: '2024-03-01',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    doctorId: 'doc-1',
    doctor: mockDoctors[0],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-09-05',
    time: '10:00 AM',
    duration: 30,
    status: 'confirmed',
    paymentStatus: 'paid',
    consultationFee: 1500,
    meetLink: 'https://meet.google.com/abc-defg-hij',
    medicalReports: [
      { id: 'mr-1', name: 'Blood Test Results', fileName: 'blood_test.pdf', fileSize: 245000, fileType: 'application/pdf', uploadedAt: '2026-09-01', url: '#' },
      { id: 'mr-2', name: 'ECG Report', fileName: 'ecg_report.pdf', fileSize: 520000, fileType: 'application/pdf', uploadedAt: '2026-09-01', url: '#' },
    ],
    createdAt: '2026-09-01',
    timeline: [
      { status: 'Booked', timestamp: '2026-09-01T10:00:00', description: 'Appointment booked successfully' },
      { status: 'Confirmed', timestamp: '2026-09-01T10:05:00', description: 'Appointment confirmed by doctor' },
    ],
  },
  {
    id: 'apt-2',
    doctorId: 'doc-3',
    doctor: mockDoctors[2],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-09-10',
    time: '09:30 AM',
    duration: 30,
    status: 'pending',
    paymentStatus: 'pending',
    consultationFee: 1000,
    createdAt: '2026-09-01',
    timeline: [
      { status: 'Booked', timestamp: '2026-09-01T14:00:00', description: 'Appointment booked successfully' },
    ],
  },
  {
    id: 'apt-3',
    doctorId: 'doc-2',
    doctor: mockDoctors[1],
    patientId: 'pat-1',
    patient: mockPatients[0],
    date: '2026-08-28',
    time: '02:00 PM',
    duration: 30,
    status: 'completed',
    paymentStatus: 'paid',
    consultationFee: 1200,
    meetLink: 'https://meet.google.com/xyz-uvwx-stu',
    createdAt: '2026-08-25',
    timeline: [
      { status: 'Booked', timestamp: '2026-08-25T09:00:00', description: 'Appointment booked successfully' },
      { status: 'Confirmed', timestamp: '2026-08-25T09:10:00', description: 'Appointment confirmed by doctor' },
      { status: 'Completed', timestamp: '2026-08-28T14:30:00', description: 'Consultation completed' },
    ],
  },
  {
    id: 'apt-4',
    doctorId: 'doc-4',
    doctor: mockDoctors[3],
    patientId: 'pat-2',
    patient: mockPatients[1],
    date: '2026-08-20',
    time: '11:00 AM',
    duration: 20,
    status: 'cancelled',
    paymentStatus: 'refunded',
    consultationFee: 800,
    createdAt: '2026-08-18',
    timeline: [
      { status: 'Booked', timestamp: '2026-08-18T15:00:00', description: 'Appointment booked successfully' },
      { status: 'Cancelled', timestamp: '2026-08-19T10:00:00', description: 'Appointment cancelled by patient' },
    ],
  },
];

export const mockReviews: Review[] = [
  { id: 'rev-1', patientId: 'pat-1', patientName: 'Tanvir Hasan', doctorId: 'doc-1', rating: 5, comment: 'Dr. Ahmed is very experienced and caring. He explained my heart condition thoroughly and provided a comprehensive treatment plan. The online consultation was seamless.', createdAt: '2026-08-20' },
  { id: 'rev-2', patientId: 'pat-2', patientName: 'Sabahat Karim', doctorId: 'doc-1', rating: 5, comment: 'Excellent experience! Dr. Ahmed was professional, attentive, and made me feel very comfortable. Highly recommended for cardiology consultations.', createdAt: '2026-08-15' },
  { id: 'rev-3', patientId: 'pat-3', patientName: 'Ariful Islam', doctorId: 'doc-1', rating: 4, comment: 'Very thorough consultation. Dr. Ahmed reviewed my reports carefully and provided clear guidance. The video quality was excellent.', createdAt: '2026-08-10' },
  { id: 'rev-4', patientId: 'pat-1', patientName: 'Tanvir Hasan', doctorId: 'doc-2', rating: 5, comment: 'Dr. Jahan resolved my skin concerns efficiently. Great bedside manner and very professional.', createdAt: '2026-08-28' },
  { id: 'rev-5', patientId: 'pat-2', patientName: 'Sabahat Karim', doctorId: 'doc-3', rating: 5, comment: 'Dr. Begum is amazing with kids! My daughter felt at ease during the entire consultation. A wonderful pediatrician.', createdAt: '2026-08-22' },
];

export const mockNotifications: Notification[] = [
  { id: 'n1', userId: 'pat-1', title: 'Appointment Confirmed', message: 'Your appointment with Dr. Rafiq Ahmed on Sep 5 has been confirmed.', type: 'success', read: false, createdAt: '2026-09-01T10:05:00', link: '/patient/appointments/apt-1' },
  { id: 'n2', userId: 'pat-1', title: 'Appointment Reminder', message: 'Your consultation with Dr. Nusrat Jahan starts in 15 minutes.', type: 'info', read: false, createdAt: '2026-08-28T13:45:00', link: '/patient/appointments/apt-3' },
  { id: 'n3', userId: 'pat-1', title: 'Payment Received', message: 'Payment of ৳1,500 for appointment with Dr. Rafiq Ahmed has been processed.', type: 'success', read: true, createdAt: '2026-09-01T10:06:00' },
  { id: 'n4', userId: 'doc-1', title: 'New Booking', message: 'Tanvir Hasan has booked an appointment for Sep 5 at 10:00 AM.', type: 'info', read: false, createdAt: '2026-09-01T10:00:00', link: '/doctor/appointments' },
  { id: 'n5', userId: 'admin', title: 'Verification Request', message: 'Dr. Nadia Rahman has submitted a new verification request.', type: 'warning', read: false, createdAt: '2026-09-01T08:00:00', link: '/admin/doctor-verification' },
  { id: 'n6', userId: 'admin', title: 'New Registration', message: 'A new patient account has been registered.', type: 'info', read: true, createdAt: '2026-09-01T07:30:00' },
];

export const mockTransactions: Transaction[] = [
  { id: 'txn-1', appointmentId: 'apt-1', doctorId: 'doc-1', doctorName: 'Dr. Rafiq Ahmed', patientId: 'pat-1', patientName: 'Tanvir Hasan', amount: 1500, status: 'paid', date: '2026-09-01' },
  { id: 'txn-2', appointmentId: 'apt-3', doctorId: 'doc-2', doctorName: 'Dr. Nusrat Jahan', patientId: 'pat-1', patientName: 'Tanvir Hasan', amount: 1200, status: 'paid', date: '2026-08-28' },
  { id: 'txn-3', appointmentId: 'apt-4', doctorId: 'doc-4', doctorName: 'Dr. Kamal Hossain', patientId: 'pat-2', patientName: 'Sabahat Karim', amount: 800, status: 'refunded', date: '2026-08-20' },
];

export const pendingVerificationDoctors: Doctor[] = [
  {
    id: 'doc-9',
    name: 'Dr. Nadia Rahman',
    email: 'nadia.rahman@email.com',
    phone: '+880 1712-000111',
    role: 'doctor',
    specialty: 'Cardiologist',
    qualification: 'MBBS, MD (Cardiology)',
    degree: 'Dhaka Medical College',
    experience: 8,
    consultationFee: 1300,
    languages: ['Bengali', 'English'],
    bio: 'Cardiologist with 8 years of experience in interventional cardiology.',
    rating: 0,
    reviewCount: 0,
    verificationStatus: 'pending',
    verified: false,
    consultationDuration: 30,
    availableSlots: [],
    createdAt: '2026-08-30',
    documents: [
      { id: 'd1', type: 'Medical Registration', name: 'BMDC Registration', fileName: 'bmdc_registration.pdf', fileSize: 340000, uploadedAt: '2026-08-30', url: '#' },
      { id: 'd2', type: 'Medical Degree', name: 'MBBS Certificate', fileName: 'mbbs_certificate.pdf', fileSize: 520000, uploadedAt: '2026-08-30', url: '#' },
      { id: 'd3', type: 'Identity Document', name: 'NID Card', fileName: 'nid_card.pdf', fileSize: 280000, uploadedAt: '2026-08-30', url: '#' },
    ],
  },
  {
    id: 'doc-10',
    name: 'Dr. Mohammed Faruk',
    email: 'mohammed.faruk@email.com',
    phone: '+880 1812-000222',
    role: 'doctor',
    specialty: 'Dermatologist',
    qualification: 'MBBS, DD',
    degree: 'Rajshahi Medical College',
    experience: 6,
    consultationFee: 1100,
    languages: ['Bengali', 'English'],
    bio: 'Dermatologist specializing in cosmetic and medical dermatology.',
    rating: 0,
    reviewCount: 0,
    verificationStatus: 'pending',
    verified: false,
    consultationDuration: 30,
    availableSlots: [],
    createdAt: '2026-08-29',
    documents: [
      { id: 'd4', type: 'Medical Registration', name: 'BMDC Registration', fileName: 'registration.pdf', fileSize: 310000, uploadedAt: '2026-08-29', url: '#' },
      { id: 'd5', type: 'Medical Degree', name: 'MBBS Certificate', fileName: 'degree.pdf', fileSize: 490000, uploadedAt: '2026-08-29', url: '#' },
    ],
  },
];

export const defaultAvailability: DayAvailability[] = [
  { day: 'sunday', available: false, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'monday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'tuesday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'wednesday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'thursday', available: true, startTime: '09:00', endTime: '17:00', slotDuration: 30 },
  { day: 'friday', available: false, startTime: '09:00', endTime: '15:00', slotDuration: 30 },
  { day: 'saturday', available: true, startTime: '09:00', endTime: '13:00', slotDuration: 30 },
];

export const monthlyRevenueData = [
  { month: 'Apr', revenue: 85000 },
  { month: 'May', revenue: 123000 },
  { month: 'Jun', revenue: 156000 },
  { month: 'Jul', revenue: 182000 },
  { month: 'Aug', revenue: 214000 },
  { month: 'Sep', revenue: 198000 },
];

export const appointmentStatsData = [
  { month: 'Apr', appointments: 45 },
  { month: 'May', appointments: 62 },
  { month: 'Jun', appointments: 78 },
  { month: 'Jul', appointments: 95 },
  { month: 'Aug', appointments: 112 },
  { month: 'Sep', appointments: 98 },
];

export const doctorGrowthData = [
  { month: 'Apr', doctors: 12 },
  { month: 'May', doctors: 18 },
  { month: 'Jun', doctors: 24 },
  { month: 'Jul', doctors: 32 },
  { month: 'Aug', doctors: 38 },
  { month: 'Sep', doctors: 42 },
];

export const patientGrowthData = [
  { month: 'Apr', patients: 85 },
  { month: 'May', patients: 124 },
  { month: 'Jun', patients: 186 },
  { month: 'Jul', patients: 245 },
  { month: 'Aug', patients: 312 },
  { month: 'Sep', patients: 389 },
];
